name: test pull docker
on:
  - push

jobs:
  test_pull_always:
    name: test always pull
    runs-on: ubuntu-latest
    container:
      image: a1012112796/rtt_ci_env:sourcery-arm
      options: --pull always

    steps:
      - uses: actions/checkout@v3
      - run: scons -v

  test_pull_not_always:
    name: test not always pull
    runs-on: ubuntu-latest
    container:
      image: a1012112796/rtt_ci_env:sourcery-arm

    steps:
      - uses: actions/checkout@v3
      - run: scons -v

